### ISSUE TITLE
JWlink sets wrong fixups

### ISSUE THREAD

**Issue by VaKonS** [Baron-von-Riedesel/jwlink#3]
Hello!
If you link object files in the attached archive ([MSlink-JWlink.zip](https://github.com/Baron-von-Riedesel/jwlink/files/5396866/MSlink-JWlink.zip), 23 kb) with Microsoft linker (from Masm 6.11), the compiled exe will work:
<code>link.exe /F /PACKCODE /SE:512 d0+natx;</code>

If you link them with JWlink, the resulting exe will be corrupted (and will hang):
<code>dpmild32.exe jwlink.exe format dos file d0.obj, natx.obj</code>

Since JWlink aligns segments to 64 bytes, and Masm to 512 bytes, I expanded header to 0x200 and compared files. Here are the differences:
<table><hd><th>Offset</th><th>MS linker code</th><th>JWlink code</th><th>Description</th></hd>
<tr><td>000A</td><td>0003</td><td>0002</td><td>MinAlloc (uninitialized data size).</td></tr>
<tr><td>000E</td><td>0254</td><td>0253</td><td>Initial SS.</td></tr>
<tr><td>0010</td><td>0020</td><td>002A</td><td>Initial SP (stack size).</td></tr>
<tr><td>001C</td><td>0001</td><td>0000</td><td>Gap between header and relocation table, probably does not matter.</td></tr>
<tr><td>028F</td><td>
90 0E E8<br>
nop<br>
push cs<br>
call ____
</td><td>
0E 3E E8<br>
push cs<br>
ds:<br>
call ____
</td><td>DS: before CALL should not be a problem.</td></tr>
<tr><td>02EF</td><td><b>0000</b><br>
mov dx, int0hand<br>
mov&nbsp;ax,&nbsp;seg&nbsp;<b>CodeSeg</b><br>
mov ds, ax<br>
mov ax, 2500h<br>
int 21h
</td><td><b>00F9</b><br>
&nbsp;<br>
mov&nbsp;ax,&nbsp;seg&nbsp;<b>00F9h</b><br>
&nbsp;<br>
&nbsp;<br>
&nbsp;
</td><td>Here is the problem №1, interrupt 0 vector (division by 0) will point to nowhere.</td></tr>
<tr><td>07F2</td><td><b>0000</b><br>
mov dx, int23hand<br>
mov&nbsp;ax,&nbsp;seg&nbsp;<b>CodeSeg</b><br>
mov ds, ax<br>
mov ax, 2523h<br>
int 21h
</td><td><b>0613</b><br>
<br>
mov&nbsp;ax,&nbsp;seg&nbsp;<b>0613h</b><br>
&nbsp;<br>
&nbsp;<br>
&nbsp;
</td><td>Problem №2, interrupt 0x23 vector (Ctrl+Break) will also point to nowhere.</td></tr>
</table>

<br>
The compiled executable simply makes "division by 0" error.<br>
In case of Microsoft linker, it displays "DIV BY 0" message.<br><br>

Files in the attached archive:
c_masm.bat, c_jwasm.bat — batch files used to link included executables;
d0_ms.exe — d0, linked with MS linker;
d0_jw._xe — d0, linked with JWlink (it is renamed to not run it accidentally, or else unpredictable code will run with disabled interrupts);
d0_jw_a._xe — same file with header expanded to 512 bytes;

d0.obj — object file, compiled with JWasm;
natx.obj — runtime library from XPL0 package (it's under GPL license and, according to package description, was compiled with MASM 5.1);

Also, folder XPL contains d0.asm, used to compile d0.obj (it was auto-generated by XPL0 compiler from http://www.xpl0.org).

Md5: 447888895e21df76fb85e8b43da3468f *MSlink-JWlink.zip

**Comment by Baron-von-Riedesel** [comment]
Sorry for the late reply. I had forgotten to set a notification address for jwlink.

Will look at this issue ASAP.

**Comment by Baron-von-Riedesel** [comment]
These 2 fixups are indeed strange:
* text found * C:\TEMP\JW\natx.dump
 Line:     Fixup: 0003  Seg Loc:Seg16 Frame:Target Target:SegIdx TgDat:3
 Line:     Fixup: 00DB  Seg Loc:Seg16 Frame:Target Target:SegIdx TgDat:2 Disp:00F9
 Line:     Fixup: 0018  Seg Loc:Seg16 Frame:Target Target:SegIdx TgDat:2
 Line:     Fixup: 001B  Seg Loc:Seg16 Frame:Target Target:SegIdx TgDat:3
 Line:     Fixup: 0044  Seg Loc:Seg16 Frame:Target Target:SegIdx TgDat:2 Disp:0613
 Line:     Fixup: 01A7  Seg Loc:Seg16 Frame:Target Target:SegIdx TgDat:2
 Line:     Fixup: 01AA  Seg Loc:Seg16 Frame:Target Target:SegIdx TgDat:3
 Line:     Fixup: 0028  Seg Loc:Seg16 Frame:Target Target:SegIdx TgDat:3
"seg16" was found 8 times in 1 files

Apparently jwlink uses the target displacement field for segment fixups (which probably is to be ignored).
Would be interesting how natx.asm looks, how one can make the assembler create a target displacement for segment refs.

**Comment by Baron-von-Riedesel** [comment]
it's fixed in v19beta16.
Currently a warning is displayed whenever a segment fixup with a target displacement is found.

**Comment by VaKonS** [comment]
Thank you very much! Exe works now.
Regarding natx.asm, the source is located at [xpl0.org](http://www.xpl0.org): http://www.xpl0.org/XSRC-31.ZIP
But there is nothing unusual in it, as far as I can tell.
1st code is in "nmain.asm":
```asm
	LEA	DX,DVZHAN	;POINT TO OUR VECTOR
	MOV	AX,SEG DVZHAN
	MOV	DS,AX
	MOV	AX,2500H
	INT	21H
```
2nd is in "nintrin1.asm":
```asm
	MOV	DX,OFFSET CTRBRK	;LOAD FAR POINTER BREAK HANDLER
	MOV	AX,SEG CTRBRK
	MOV	DS,AX
	MOV	AX,02523H	;SET INT 23H VECTOR
	INT	21H
```

The OMF specification (ftp://ftp.openwatcom.org/devel/docs/omf.pdf) mentions that displacement can exist for SEGDEF, GRPDEF and EXTDEF target methods:
> The Target Displacement field, a 16-bit or 32-bit field, is present only if the P bit in the Fix Data field is set to 0, in which case the Target Displacement field contains the offset used in methods 0, 1, and 2 of specifying a TARGET.

Currently I'm trying to make own omf parser, to get all records details, but haven't succeeded much yet. :)
And again, thank you very much!
